library(fda)
library(Metrics)
library(MASS)
library(Deriv)
library(tidyverse)
library(MatrixCorrelation)

source('General_Function/Function_general.R')
source('General_Function/Error_Sim.R')
source('General_Function/Correlation_Sim.R')
source('General_Function/MAE_Sim.R')

# source('Data_Simulation/Data_Input1.R')
# source('Data_Simulation/Data_Input2.R')
# source('Data_Simulation/Function_Output.R')
# source('Data_Simulation/Data_Output.R')
source('Data_ADNI/Data_Output.R')

source('NN/update_parameters.R')
source('NN/predict.R')
source('NN/initialize_parameters.R')
source('NN/forward_propagation.R')
source('NN/backward_propagation.R')
source('NN/update_adadelta_nn.R')
source('NN/initialize_adadelta_nn.R')

#add another layer
source('FNNdeep/update_parameters2.R')
source('FNNdeep/update_parameters_adadelta.R')
source('FNNdeep/predict2.R')
source('FNNdeep/initialize_parameters2.R')
source('FNNdeep/initialize_adadelta_parameters.R')
source('FNNdeep/forward_propagation2.R')
source('FNNdeep/backward_propagation2.R')

source('FNNwide/backward_propagation_pre.R')
source('FNNwide/forward_propagation_pre.R')
source('FNNwide/initialize_pre.R')
source('FNNwide/initialize_pre_adadelta.R')
source('FNNwide/update_parameters_pre.R')
source('FNNwide/update_adadelta_pre.R')

source('FNNwide/predict_wide.R')
source('FNNwide/initialize_parameters_wide.R')
source('FNNwide/initialize_wide_adadelta.R')
source('FNNwide/forward_propagation_wide.R')
source('FNNwide/backward_propagation_wide.R')
source('FNNwide/update_parameters_wide.R')
source('FNNwide/update_adadelta_wide.R')

source('NN.R')
source('FNNdeep.R')
source('FNNwide.R')
